### ISSUE TITLE
Hackathon/Data Challenges: Contact URLs don't work

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/datalab-main-site#1]
The URLs in the contact for external websites don't appear to be functioning. The page simply reloads.

Example at https://stage-datalab.library.ucdavis.edu/hackathon/californiawater-data-challenge/ 

On a related note, is it possible to auto hide the `https//` and ending `/` on urls? For example:

| Current | Desired |
| --- | --- |
| ![Screenshot 2024-06-13 at 10 22 20 AM](https://github.com/UCDavisLibrary/datalab-main-site/assets/17831969/928980d7-7749-4628-814d-0b5d4398be1f) | ![Screenshot 2024-06-13 at 10 23 05 AM](https://github.com/UCDavisLibrary/datalab-main-site/assets/17831969/235b0489-ba59-4d57-ab9f-80443d8a1c13) |

I see that I can put in a URL without whose pieces and it appears as desired, but I wouldn't expect datalab content people to think about or do that one they take over management of it.

**Comment by wrenaria** [comment]
Is there a way to prevent long urls/emails from breaking on smaller viewports? Wrapping them maybe?

![Screenshot 2024-06-13 at 4 12 15 PM](https://github.com/UCDavisLibrary/datalab-main-site/assets/17831969/e87e83f3-c445-4ad4-a701-08c1049244c0)

**Comment by spelkey-ucd** [comment]
deployed to stage build: v0.0.9.20
