### ISSUE TITLE
Hackathon/Data Challenges: Single page entries treat featured images as pages

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/datalab-main-site#2]
Single page data challenges appear to treat the images assigned in the metadata as child pages. I tried removing all of the image assignments from both the hackathon metadata and the global page settings, but the sidebar link to the image persisted. 

Example at https://stage-datalab.library.ucdavis.edu/hackathon/californiawater-data-challenge/ 

![Screenshot 2024-06-13 at 10 48 49 AM](https://github.com/UCDavisLibrary/datalab-main-site/assets/17831969/f27f86bb-6d11-4923-9e2d-efdb18b770ce)

**Comment by spelkey-ucd** [comment]
deployed to stage build: v0.0.9.20
