### ISSUE TITLE
Hackathon/Data Challenges: Change URL slug and editor labels

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/datalab-main-site#3]
This request is about URL slugs:
![Screenshot 2024-06-13 at 2 25 07 PM](https://github.com/UCDavisLibrary/datalab-main-site/assets/17831969/dfcdd767-88aa-4446-9958-30b065da6c41)

Right now all of the hackathons and challenges are showing`/hackathon/` in the URL. Can it be changed to `/challenge/` instead (or change according to assigned type, either way is fine)? I think the word challenge can be interpreted more broadly to encompass both types, but hackathon feels much more specific and not always appropriate to all events. 

Relatedly, if the terminology can be standardized in the editor, that would be less confusing as well:

![Screenshot 2024-06-13 at 2 26 17 PM](https://github.com/UCDavisLibrary/datalab-main-site/assets/17831969/cf431783-70b1-4da1-bff7-9ebd5d8e954c)

**Comment by spelkey-ucd** [comment]
deployed to stage build: v0.0.9.20
